//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDLKC2016WSSample.PublicationOutput20ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
    [System.SerializableAttribute()]
    public partial class InfoShareFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InfoShareErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InfoShareErrorNumber {
            get {
                return this.InfoShareErrorNumberField;
            }
            set {
                if ((this.InfoShareErrorNumberField.Equals(value) != true)) {
                    this.InfoShareErrorNumberField = value;
                    this.RaisePropertyChanged("InfoShareErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLDetail {
            get {
                return this.XMLDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLDetailField, value) != true)) {
                    this.XMLDetailField = value;
                    this.RaisePropertyChanged("XMLDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ISHStatusgroup", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API20/")]
    public enum ISHStatusgroup : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHReleasedStates = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHReleasedOrDraftStates = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHOutOfDateOrReleasedStates = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISHNoStatusFilter = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/", ConfigurationName="PublicationOutput20ServiceReference.PublicationOutput")]
    public interface PublicationOutput {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Creat" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Creat" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Creat" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Create(string logicalId, ref string version, string outputFormat, string language, string xmlMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublish", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublishResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublishInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string CancelPublish(string logicalId, string version, string outputFormat, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublishByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublishByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Cance" +
            "lPublishByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string CancelPublishByIshLngRef(long lngRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Delete(string logicalId, string version, string outputFormat, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "eByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "eByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Delet" +
            "eByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string DeleteByIshLngRef(long lngRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taData", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taDataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string SetMetaData(string logicalId, ref string version, string outputFormat, string language, string xmlRequiredCurrentState, string xmlMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taDataByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taDataByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/SetMe" +
            "taDataByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string SetMetaDataByIshLngRef(long lngRef, string xmlRequiredCurrentState, string xmlMetadata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "sh", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "shResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "shInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Publish(string logicalId, string version, string outputFormat, string language, ref string eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "shByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "shByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Publi" +
            "shByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string PublishByIshLngRef(long lngRef, ref string eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "se", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "seResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "seInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Release(string logicalId, string version, string outputFormat, string language, ref string xmlBaselineReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "seByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "seByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Relea" +
            "seByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string ReleaseByIshLngRef(long lngRef, ref string xmlBaselineReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Find", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/FindR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/FindI" +
            "nfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string Find(string xmlMetadataFilter, string xmlRequestedMetadata, ref string xmlObjectList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetMe" +
            "taData", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetMe" +
            "taDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetMe" +
            "taDataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string GetMetaData(string logicalId, string version, string outputFormat, string language, string xmlRequestedMetadata, ref string xmlObjectList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaData", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaDataInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string RetrieveMetaData(string logicalId, string version, SDLKC2016WSSample.PublicationOutput20ServiceReference.ISHStatusgroup statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata, ref string xmlObjectList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "port", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "portResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "portInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string GetReport(string logicalId, string version, string outputFormat, string language, ref string xmlReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "portByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "portByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetRe" +
            "portByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string GetReportByIshLngRef(long lngRef, ref string xmlReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaDataByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaDataByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/Retri" +
            "eveMetaDataByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string RetrieveMetaDataByIshLngRef(string lngRefs, string xmlRequestedMetadata, ref string xmlObjectList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetDa" +
            "taObjectInfoByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetDa" +
            "taObjectInfoByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetDa" +
            "taObjectInfoByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlIshDataObject")]
        string GetDataObjectInfoByIshLngRef(long lngRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetNe" +
            "xtDataObjectChunkByIshLngRef", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetNe" +
            "xtDataObjectChunkByIshLngRefResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SDLKC2016WSSample.PublicationOutput20ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API20/PublicationOutput/GetNe" +
            "xtDataObjectChunkByIshLngRefInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API20/")]
        void GetNextDataObjectChunkByIshLngRef(long lngRef, string edGUID, ref long offSet, ref int size, out byte[] bytes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublicationOutputChannel : SDLKC2016WSSample.PublicationOutput20ServiceReference.PublicationOutput, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicationOutputClient : System.ServiceModel.ClientBase<SDLKC2016WSSample.PublicationOutput20ServiceReference.PublicationOutput>, SDLKC2016WSSample.PublicationOutput20ServiceReference.PublicationOutput {
        
        public PublicationOutputClient() {
        }
        
        public PublicationOutputClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicationOutputClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicationOutputClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicationOutputClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Create(string logicalId, ref string version, string outputFormat, string language, string xmlMetadata) {
            return base.Channel.Create(logicalId, ref version, outputFormat, language, xmlMetadata);
        }
        
        public string CancelPublish(string logicalId, string version, string outputFormat, string language) {
            return base.Channel.CancelPublish(logicalId, version, outputFormat, language);
        }
        
        public string CancelPublishByIshLngRef(long lngRef) {
            return base.Channel.CancelPublishByIshLngRef(lngRef);
        }
        
        public string Delete(string logicalId, string version, string outputFormat, string language) {
            return base.Channel.Delete(logicalId, version, outputFormat, language);
        }
        
        public string DeleteByIshLngRef(long lngRef) {
            return base.Channel.DeleteByIshLngRef(lngRef);
        }
        
        public string SetMetaData(string logicalId, ref string version, string outputFormat, string language, string xmlRequiredCurrentState, string xmlMetadata) {
            return base.Channel.SetMetaData(logicalId, ref version, outputFormat, language, xmlRequiredCurrentState, xmlMetadata);
        }
        
        public string SetMetaDataByIshLngRef(long lngRef, string xmlRequiredCurrentState, string xmlMetadata) {
            return base.Channel.SetMetaDataByIshLngRef(lngRef, xmlRequiredCurrentState, xmlMetadata);
        }
        
        public string Publish(string logicalId, string version, string outputFormat, string language, ref string eventId) {
            return base.Channel.Publish(logicalId, version, outputFormat, language, ref eventId);
        }
        
        public string PublishByIshLngRef(long lngRef, ref string eventId) {
            return base.Channel.PublishByIshLngRef(lngRef, ref eventId);
        }
        
        public string Release(string logicalId, string version, string outputFormat, string language, ref string xmlBaselineReport) {
            return base.Channel.Release(logicalId, version, outputFormat, language, ref xmlBaselineReport);
        }
        
        public string ReleaseByIshLngRef(long lngRef, ref string xmlBaselineReport) {
            return base.Channel.ReleaseByIshLngRef(lngRef, ref xmlBaselineReport);
        }
        
        public string Find(string xmlMetadataFilter, string xmlRequestedMetadata, ref string xmlObjectList) {
            return base.Channel.Find(xmlMetadataFilter, xmlRequestedMetadata, ref xmlObjectList);
        }
        
        public string GetMetaData(string logicalId, string version, string outputFormat, string language, string xmlRequestedMetadata, ref string xmlObjectList) {
            return base.Channel.GetMetaData(logicalId, version, outputFormat, language, xmlRequestedMetadata, ref xmlObjectList);
        }
        
        public string RetrieveMetaData(string logicalId, string version, SDLKC2016WSSample.PublicationOutput20ServiceReference.ISHStatusgroup statusFilter, string xmlMetadataFilter, string xmlRequestedMetadata, ref string xmlObjectList) {
            return base.Channel.RetrieveMetaData(logicalId, version, statusFilter, xmlMetadataFilter, xmlRequestedMetadata, ref xmlObjectList);
        }
        
        public string GetReport(string logicalId, string version, string outputFormat, string language, ref string xmlReport) {
            return base.Channel.GetReport(logicalId, version, outputFormat, language, ref xmlReport);
        }
        
        public string GetReportByIshLngRef(long lngRef, ref string xmlReport) {
            return base.Channel.GetReportByIshLngRef(lngRef, ref xmlReport);
        }
        
        public string RetrieveMetaDataByIshLngRef(string lngRefs, string xmlRequestedMetadata, ref string xmlObjectList) {
            return base.Channel.RetrieveMetaDataByIshLngRef(lngRefs, xmlRequestedMetadata, ref xmlObjectList);
        }
        
        public string GetDataObjectInfoByIshLngRef(long lngRef) {
            return base.Channel.GetDataObjectInfoByIshLngRef(lngRef);
        }
        
        public void GetNextDataObjectChunkByIshLngRef(long lngRef, string edGUID, ref long offSet, ref int size, out byte[] bytes) {
            base.Channel.GetNextDataObjectChunkByIshLngRef(lngRef, edGUID, ref offSet, ref size, out bytes);
        }
    }
}
